export const elementIcons = [
  "el-icon-platform-eleme",
  "el-icon-eleme",
  "el-icon-delete-solid",
  "el-icon-delete",
  "el-icon-s-tools",
  "el-icon-setting",
  "el-icon-user-solid",
  "el-icon-user",
  "el-icon-phone",
  "el-icon-phone-outline",
  "el-icon-more",
  "el-icon-more-outline",
  "el-icon-star-on",
  "el-icon-star-off",
  "el-icon-s-goods",
  "el-icon-goods",
  "el-icon-warning",
  "el-icon-warning-outline",
  "el-icon-question",
  "el-icon-info",
  "el-icon-remove",
  "el-icon-circle-plus",
  "el-icon-success",
  "el-icon-error",
  "el-icon-zoom-in",
  "el-icon-zoom-out",
  "el-icon-remove-outline",
  "el-icon-circle-plus-outline",
  "el-icon-circle-check",
  "el-icon-circle-close",
  "el-icon-s-help",
  "el-icon-help",
  "el-icon-minus",
  "el-icon-plus",
  "el-icon-check",
  "el-icon-close",
  "el-icon-picture",
  "el-icon-picture-outline",
  "el-icon-picture-outline-round",
  "el-icon-upload",
  "el-icon-upload2",
  "el-icon-download",
  "el-icon-camera-solid",
  "el-icon-camera",
  "el-icon-video-camera-solid",
  "el-icon-video-camera",
  "el-icon-message-solid",
  "el-icon-bell",
  "el-icon-s-cooperation",
  "el-icon-s-order",
  "el-icon-s-platform",
  "el-icon-s-fold",
  "el-icon-s-unfold",
  "el-icon-s-operation",
  "el-icon-s-promotion",
  "el-icon-s-home",
  "el-icon-s-release",
  "el-icon-s-ticket",
  "el-icon-s-management",
  "el-icon-s-open",
  "el-icon-s-shop",
  "el-icon-s-marketing",
  "el-icon-s-flag",
  "el-icon-s-comment",
  "el-icon-s-finance",
  "el-icon-s-claim",
  "el-icon-s-custom",
  "el-icon-s-opportunity",
  "el-icon-s-data",
  "el-icon-s-check",
  "el-icon-s-grid",
  "el-icon-menu",
  "el-icon-share",
  "el-icon-d-caret",
  "el-icon-caret-left",
  "el-icon-caret-right",
  "el-icon-caret-bottom",
  "el-icon-caret-top",
  "el-icon-bottom-left",
  "el-icon-bottom-right",
  "el-icon-back",
  "el-icon-right",
  "el-icon-bottom",
  "el-icon-top",
  "el-icon-top-left",
  "el-icon-top-right",
  "el-icon-arrow-left",
  "el-icon-arrow-right",
  "el-icon-arrow-down",
  "el-icon-arrow-up",
  "el-icon-d-arrow-left",
  "el-icon-d-arrow-right",
  "el-icon-video-pause",
  "el-icon-video-play",
  "el-icon-refresh",
  "el-icon-refresh-right",
  "el-icon-refresh-left",
  "el-icon-finished",
  "el-icon-sort",
  "el-icon-sort-up",
  "el-icon-sort-down",
  "el-icon-rank",
  "el-icon-loading",
  "el-icon-view",
  "el-icon-c-scale-to-original",
  "el-icon-date",
  "el-icon-edit",
  "el-icon-edit-outline",
  "el-icon-folder",
  "el-icon-folder-opened",
  "el-icon-folder-add",
  "el-icon-folder-remove",
  "el-icon-folder-delete",
  "el-icon-folder-checked",
  "el-icon-tickets",
  "el-icon-document-remove",
  "el-icon-document-delete",
  "el-icon-document-copy",
  "el-icon-document-checked",
  "el-icon-document",
  "el-icon-document-add",
  "el-icon-printer",
  "el-icon-paperclip",
  "el-icon-takeaway-box",
  "el-icon-search",
  "el-icon-monitor",
  "el-icon-attract",
  "el-icon-mobile",
  "el-icon-scissors",
  "el-icon-umbrella",
  "el-icon-headset",
  "el-icon-brush",
  "el-icon-mouse",
  "el-icon-coordinate",
  "el-icon-magic-stick",
  "el-icon-reading",
  "el-icon-data-line",
  "el-icon-data-board",
  "el-icon-pie-chart",
  "el-icon-data-analysis",
  "el-icon-collection-tag",
  "el-icon-film",
  "el-icon-suitcase",
  "el-icon-suitcase-1",
  "el-icon-receiving",
  "el-icon-collection",
  "el-icon-files",
  "el-icon-notebook-1",
  "el-icon-notebook-2",
  "el-icon-toilet-paper",
  "el-icon-office-building",
  "el-icon-school",
  "el-icon-table-lamp",
  "el-icon-house",
  "el-icon-no-smoking",
  "el-icon-smoking",
  "el-icon-shopping-cart-full",
  "el-icon-shopping-cart-1",
  "el-icon-shopping-cart-2",
  "el-icon-shopping-bag-1",
  "el-icon-shopping-bag-2",
  "el-icon-sold-out",
  "el-icon-sell",
  "el-icon-present",
  "el-icon-box",
  "el-icon-bank-card",
  "el-icon-money",
  "el-icon-coin",
  "el-icon-wallet",
  "el-icon-discount",
  "el-icon-price-tag",
  "el-icon-news",
  "el-icon-guide",
  "el-icon-male",
  "el-icon-female",
  "el-icon-thumb",
  "el-icon-cpu",
  "el-icon-link",
  "el-icon-connection",
  "el-icon-open",
  "el-icon-turn-off",
  "el-icon-set-up",
  "el-icon-chat-round",
  "el-icon-chat-line-round",
  "el-icon-chat-square",
  "el-icon-chat-dot-round",
  "el-icon-chat-dot-square",
  "el-icon-chat-line-square",
  "el-icon-message",
  "el-icon-postcard",
  "el-icon-position",
  "el-icon-turn-off-microphone",
  "el-icon-microphone",
  "el-icon-close-notification",
  "el-icon-bangzhu",
  "el-icon-time",
  "el-icon-odometer",
  "el-icon-crop",
  "el-icon-aim",
  "el-icon-switch-button",
  "el-icon-full-screen",
  "el-icon-copy-document",
  "el-icon-mic",
  "el-icon-stopwatch",
  "el-icon-medal-1",
  "el-icon-medal",
  "el-icon-trophy",
  "el-icon-trophy-1",
  "el-icon-first-aid-kit",
  "el-icon-discover",
  "el-icon-place",
  "el-icon-location",
  "el-icon-location-outline",
  "el-icon-location-information",
  "el-icon-add-location",
  "el-icon-delete-location",
  "el-icon-map-location",
  "el-icon-alarm-clock",
  "el-icon-timer",
  "el-icon-watch-1",
  "el-icon-watch",
  "el-icon-lock",
  "el-icon-unlock",
  "el-icon-key",
  "el-icon-service",
  "el-icon-mobile-phone",
  "el-icon-bicycle",
  "el-icon-truck",
  "el-icon-ship",
  "el-icon-basketball",
  "el-icon-football",
  "el-icon-soccer",
  "el-icon-baseball",
  "el-icon-wind-power",
  "el-icon-light-rain",
  "el-icon-lightning",
  "el-icon-heavy-rain",
  "el-icon-sunrise",
  "el-icon-sunrise-1",
  "el-icon-sunset",
  "el-icon-sunny",
  "el-icon-cloudy",
  "el-icon-partly-cloudy",
  "el-icon-cloudy-and-sunny",
  "el-icon-moon",
  "el-icon-moon-night",
  "el-icon-dish",
  "el-icon-dish-1",
  "el-icon-food",
  "el-icon-chicken",
  "el-icon-fork-spoon",
  "el-icon-knife-fork",
  "el-icon-burger",
  "el-icon-tableware",
  "el-icon-sugar",
  "el-icon-dessert",
  "el-icon-ice-cream",
  "el-icon-hot-water",
  "el-icon-water-cup",
  "el-icon-coffee-cup",
  "el-icon-cold-drink",
  "el-icon-goblet",
  "el-icon-goblet-full",
  "el-icon-goblet-square",
  "el-icon-goblet-square-full",
  "el-icon-refrigerator",
  "el-icon-grape",
  "el-icon-watermelon",
  "el-icon-cherry",
  "el-icon-apple",
  "el-icon-pear",
  "el-icon-orange",
  "el-icon-coffee",
  "el-icon-ice-tea",
  "el-icon-ice-drink",
  "el-icon-milk-tea",
  "el-icon-potato-strips",
  "el-icon-lollipop",
  "el-icon-ice-cream-square",
  "el-icon-ice-cream-round",
];

export const fontAwesomeFreeSolid = [];
export const fontAwesomeFreeRegular = [];
export const fontAwesomeBrands = [
  "fa-brands fa-facebook fa-fw",
  "fa-brands fa-twitter fa-fw",
  "fa-brands fa-instagram fa-fw",
  "fa-brands fa-tiktok fa-fw",
  "fa-brands fa-linkedin fa-fw",
  "fa-brands fa-github fa-fw",
  "fa-brands fa-discord fa-fw",
  "fa-brands fa-youtube fa-fw",
  "fa-brands fa-wordpress fa-fw",
  "fa-brands fa-slack fa-fw",
  "fa-brands fa-figma fa-fw",
  "fa-brands fa-apple fa-fw",
  "fa-brands fa-google fa-fw",
  "fa-brands fa-stripe fa-fw",
  "fa-brands fa-algolia fa-fw",
  "fa-brands fa-docker fa-fw",
  "fa-brands fa-windows fa-fw",
  "fa-brands fa-paypal fa-fw",
  "fa-brands fa-stack-overflow fa-fw",
  "fa-brands fa-kickstarter fa-fw",
  "fa-brands fa-dribbble fa-fw",
  "fa-brands fa-dropbox fa-fw",
  "fa-brands fa-squarespace fa-fw",
  "fa-brands fa-android fa-fw",
  "fa-brands fa-shopify fa-fw",
  "fa-brands fa-medium fa-fw",
  "fa-brands fa-codepen fa-fw",
  "fa-brands fa-cloudflare fa-fw",
  "fa-brands fa-airbnb fa-fw",
  "fa-brands fa-vimeo fa-fw",
  "fa-brands fa-whatsapp fa-fw",
  "fa-brands fa-intercom fa-fw",
  "fa-brands fa-usps fa-fw",
  "fa-brands fa-wix fa-fw",
  "fa-brands fa-line fa-fw",
  "fa-brands fa-behance fa-fw",
  "fa-brands fa-openid fa-fw",
  "fa-brands fa-product-hunt fa-fw",
  "fa-brands fa-internet-explorer fa-fw",
  "fa-brands fa-pagelines fa-fw",
  "fa-brands fa-teamspeak fa-fw",
  "fa-brands fa-html5 fa-fw",
  "fa-brands fa-telegram fa-fw",
  "fa-brands fa-pinterest fa-fw",
  "fa-brands fa-dashcube fa-fw",
  "fa-brands fa-ideal fa-fw",
  "fa-brands fa-salesforce fa-fw",
  "fa-brands fa-readme fa-fw",
  "fa-brands fa-free-code-camp fa-fw",
  "fa-brands fa-soundcloud fa-fw",
  "fa-brands fa-square-twitter fa-fw",
  "fa-brands fa-accessible-icon fa-fw",
  "fa-brands fa-cc-visa fa-fw",
  "fa-brands fa-goodreads-g fa-fw",
  "fa-brands fa-google-play fa-fw",
  "fa-brands fa-react fa-fw",
  "fa-brands fa-wikipedia-w fa-fw",
  "fa-brands fa-square-js fa-fw",
  "fa-brands fa-java fa-fw",
  "fa-brands fa-square-pinterest fa-fw",
  "fa-brands fa-python fa-fw",
  "fa-brands fa-skype fa-fw",
  "fa-brands fa-linux fa-fw",
  "fa-brands fa-node fa-fw",
  "fa-brands fa-rebel fa-fw",
  "fa-brands fa-etsy fa-fw",
  "fa-brands fa-discourse fa-fw",
  "fa-brands fa-amazon fa-fw",
  "fa-brands fa-glide-g fa-fw",
  "fa-brands fa-gitlab fa-fw",
  "fa-brands fa-spotify fa-fw",
  "fa-brands fa-think-peaks fa-fw",
  "fa-brands fa-microsoft fa-fw",
  "fa-brands fa-elementor fa-fw",
  "fa-brands fa-pied-piper fa-fw",
  "fa-brands fa-square-youtube fa-fw",
  "fa-brands fa-cc-mastercard fa-fw",
  "fa-brands fa-facebook-messenger fa-fw",
  "fa-brands fa-atlassian fa-fw",
  "fa-brands fa-playstation fa-fw",
  "fa-brands fa-fly fa-fw",
  "fa-brands fa-meetup fa-fw",
  "fa-brands fa-twitch fa-fw",
  "fa-brands fa-waze fa-fw",
  "fa-brands fa-zhihu fa-fw",
  "fa-brands fa-yoast fa-fw",
  "fa-brands fa-yelp fa-fw",
  "fa-brands fa-yarn fa-fw",
  "fa-brands fa-yandex-international fa-fw",
  "fa-brands fa-yandex fa-fw",
  "fa-brands fa-yammer fa-fw",
  "fa-brands fa-yahoo fa-fw",
  "fa-brands fa-y-combinator fa-fw",
  "fa-brands fa-xing fa-fw",
  "fa-brands fa-xbox fa-fw",
  "fa-brands fa-wpressr fa-fw",
  "fa-brands fa-wpforms fa-fw",
  "fa-brands fa-wpexplorer fa-fw",
  "fa-brands fa-wpbeginner fa-fw",
  "fa-brands fa-wordpress-simple fa-fw",
  "fa-brands fa-wolf-pack-battalion fa-fw",
  "fa-brands fa-wodu fa-fw",
  "fa-brands fa-wizards-of-the-coast fa-fw",
  "fa-brands fa-wirsindhandwerk fa-fw",
  "fa-brands fa-whmcs fa-fw",
  "fa-brands fa-weixin fa-fw",
  "fa-brands fa-weibo fa-fw",
  "fa-brands fa-weebly fa-fw",
  "fa-brands fa-watchman-monitoring fa-fw",
  "fa-brands fa-vuejs fa-fw",
  "fa-brands fa-vnv fa-fw",
  "fa-brands fa-vk fa-fw",
  "fa-brands fa-vine fa-fw",
  "fa-brands fa-vimeo-v fa-fw",
  "fa-brands fa-viber fa-fw",
  "fa-brands fa-viadeo fa-fw",
  "fa-brands fa-viacoin fa-fw",
  "fa-brands fa-vaadin fa-fw",
  "fa-brands fa-ussunnah fa-fw",
  "fa-brands fa-usb fa-fw",
  "fa-brands fa-ups fa-fw",
  "fa-brands fa-untappd fa-fw",
  "fa-brands fa-unsplash fa-fw",
  "fa-brands fa-unity fa-fw",
  "fa-brands fa-uniregistry fa-fw",
  "fa-brands fa-uncharted fa-fw",
  "fa-brands fa-umbraco fa-fw",
  "fa-brands fa-uikit fa-fw",
  "fa-brands fa-ubuntu fa-fw",
  "fa-brands fa-uber fa-fw",
  "fa-brands fa-typo3 fa-fw",
  "fa-brands fa-tumblr fa-fw",
  "fa-brands fa-trello fa-fw",
  "fa-brands fa-trade-federation fa-fw",
  "fa-brands fa-themeisle fa-fw",
  "fa-brands fa-themeco fa-fw",
  "fa-brands fa-the-red-yeti fa-fw",
  "fa-brands fa-tencent-weibo fa-fw",
  "fa-brands fa-symfony fa-fw",
  "fa-brands fa-swift fa-fw",
  "fa-brands fa-suse fa-fw",
  "fa-brands fa-supple fa-fw",
  "fa-brands fa-superpowers fa-fw",
  "fa-brands fa-stumbleupon-circle fa-fw",
  "fa-brands fa-stumbleupon fa-fw",
  "fa-brands fa-studiovinari fa-fw",
  "fa-brands fa-stubber fa-fw",
  "fa-brands fa-stripe-s fa-fw",
  "fa-brands fa-strava fa-fw",
  "fa-brands fa-sticker-mule fa-fw",
  "fa-brands fa-steam-symbol fa-fw",
  "fa-brands fa-steam fa-fw",
  "fa-brands fa-staylinked fa-fw",
  "fa-brands fa-stackpath fa-fw",
  "fa-brands fa-stack-exchange fa-fw",
  "fa-brands fa-square-xing fa-fw",
  "fa-brands fa-square-whatsapp fa-fw",
  "fa-brands fa-square-vimeo fa-fw",
  "fa-brands fa-square-viadeo fa-fw",
  "fa-brands fa-square-tumblr fa-fw",
  "fa-brands fa-square-steam fa-fw",
  "fa-brands fa-square-snapchat fa-fw",
  "fa-brands fa-square-reddit fa-fw",
  "fa-brands fa-square-pied-piper fa-fw",
  "fa-brands fa-square-odnoklassniki fa-fw",
  "fa-brands fa-square-lastfm fa-fw",
  "fa-brands fa-square-instagram fa-fw",
  "fa-brands fa-square-hacker-news fa-fw",
  "fa-brands fa-square-google-plus fa-fw",
  "fa-brands fa-square-gitlab fa-fw",
  "fa-brands fa-square-github fa-fw",
  "fa-brands fa-square-git fa-fw",
  "fa-brands fa-square-font-awesome-stroke fa-fw",
  "fa-brands fa-square-font-awesome fa-fw",
  "fa-brands fa-square-facebook fa-fw",
  "fa-brands fa-square-dribbble fa-fw",
  "fa-brands fa-square-behance fa-fw",
  "fa-brands fa-speaker-deck fa-fw",
  "fa-brands fa-speakap fa-fw",
  "fa-brands fa-space-awesome fa-fw",
  "fa-brands fa-sourcetree fa-fw",
  "fa-brands fa-snapchat fa-fw",
  "fa-brands fa-slideshare fa-fw",
  "fa-brands fa-skyatlas fa-fw",
  "fa-brands fa-sketch fa-fw",
  "fa-brands fa-sitrox fa-fw",
  "fa-brands fa-sith fa-fw",
  "fa-brands fa-sistrix fa-fw",
  "fa-brands fa-simplybuilt fa-fw",
  "fa-brands fa-shopware fa-fw",
  "fa-brands fa-shirtsinbulk fa-fw",
  "fa-brands fa-servicestack fa-fw",
  "fa-brands fa-sellsy fa-fw",
  "fa-brands fa-sellcast fa-fw",
  "fa-brands fa-searchengin fa-fw",
  "fa-brands fa-scribd fa-fw",
  "fa-brands fa-screenpal fa-fw",
  "fa-brands fa-schlix fa-fw",
  "fa-brands fa-sass fa-fw",
  "fa-brands fa-safari fa-fw",
  "fa-brands fa-rust fa-fw",
  "fa-brands fa-rockrms fa-fw",
  "fa-brands fa-rocketchat fa-fw",
  "fa-brands fa-rev fa-fw",
  "fa-brands fa-resolving fa-fw",
  "fa-brands fa-researchgate fa-fw",
  "fa-brands fa-replyd fa-fw",
  "fa-brands fa-renren fa-fw",
  "fa-brands fa-redhat fa-fw",
  "fa-brands fa-reddit-alien fa-fw",
  "fa-brands fa-reddit fa-fw",
  "fa-brands fa-red-river fa-fw",
  "fa-brands fa-reacteurope fa-fw",
  "fa-brands fa-ravelry fa-fw",
  "fa-brands fa-raspberry-pi fa-fw",
  "fa-brands fa-r-project fa-fw",
  "fa-brands fa-quora fa-fw",
  "fa-brands fa-quinscape fa-fw",
  "fa-brands fa-qq fa-fw",
  "fa-brands fa-pushed fa-fw",
  "fa-brands fa-pix fa-fw",
  "fa-brands fa-pinterest-p fa-fw",
  "fa-brands fa-pied-piper-pp fa-fw",
  "fa-brands fa-pied-piper-hat fa-fw",
  "fa-brands fa-pied-piper-alt fa-fw",
  "fa-brands fa-php fa-fw",
  "fa-brands fa-phoenix-squadron fa-fw",
  "fa-brands fa-phoenix-framework fa-fw",
  "fa-brands fa-phabricator fa-fw",
  "fa-brands fa-periscope fa-fw",
  "fa-brands fa-perbyte fa-fw",
  "fa-brands fa-patreon fa-fw",
  "fa-brands fa-palfed fa-fw",
  "fa-brands fa-page4 fa-fw",
  "fa-brands fa-padlet fa-fw",
  "fa-brands fa-osi fa-fw",
  "fa-brands fa-orcid fa-fw",
  "fa-brands fa-optin-monster fa-fw",
  "fa-brands fa-opera fa-fw",
  "fa-brands fa-opencart fa-fw",
  "fa-brands fa-old-republic fa-fw",
  "fa-brands fa-odysee fa-fw",
  "fa-brands fa-odnoklassniki fa-fw",
  "fa-brands fa-octopus-deploy fa-fw",
  "fa-brands fa-nutritionix fa-fw",
  "fa-brands fa-ns8 fa-fw",
  "fa-brands fa-npm fa-fw",
  "fa-brands fa-node-js fa-fw",
  "fa-brands fa-nimblr fa-fw",
  "fa-brands fa-nfc-symbol fa-fw",
  "fa-brands fa-nfc-directional fa-fw",
  "fa-brands fa-neos fa-fw",
  "fa-brands fa-napster fa-fw",
  "fa-brands fa-monero fa-fw",
  "fa-brands fa-modx fa-fw",
  "fa-brands fa-mizuni fa-fw",
  "fa-brands fa-mixer fa-fw",
  "fa-brands fa-mixcloud fa-fw",
  "fa-brands fa-mix fa-fw",
  "fa-brands fa-microblog fa-fw",
  "fa-brands fa-meta fa-fw",
  "fa-brands fa-mendeley fa-fw",
  "fa-brands fa-megaport fa-fw",
  "fa-brands fa-medrt fa-fw",
  "fa-brands fa-medapps fa-fw",
  "fa-brands fa-mdb fa-fw",
  "fa-brands fa-maxcdn fa-fw",
  "fa-brands fa-mastodon fa-fw",
  "fa-brands fa-markdown fa-fw",
  "fa-brands fa-mandalorian fa-fw",
  "fa-brands fa-mailchimp fa-fw",
  "fa-brands fa-magento fa-fw",
  "fa-brands fa-lyft fa-fw",
  "fa-brands fa-linode fa-fw",
  "fa-brands fa-linkedin-in fa-fw",
  "fa-brands fa-less fa-fw",
  "fa-brands fa-leanpub fa-fw",
  "fa-brands fa-lastfm fa-fw",
  "fa-brands fa-laravel fa-fw",
  "fa-brands fa-korvue fa-fw",
  "fa-brands fa-kickstarter-k fa-fw",
  "fa-brands fa-keycdn fa-fw",
  "fa-brands fa-keybase fa-fw",
  "fa-brands fa-kaggle fa-fw",
  "fa-brands fa-jsfiddle fa-fw",
  "fa-brands fa-js fa-fw",
  "fa-brands fa-joomla fa-fw",
  "fa-brands fa-joget fa-fw",
  "fa-brands fa-jira fa-fw",
  "fa-brands fa-jenkins fa-fw",
  "fa-brands fa-jedi-order fa-fw",
  "fa-brands fa-itunes-note fa-fw",
  "fa-brands fa-itunes fa-fw",
  "fa-brands fa-itch-io fa-fw",
  "fa-brands fa-ioxhost fa-fw",
  "fa-brands fa-invision fa-fw",
  "fa-brands fa-instalod fa-fw",
  "fa-brands fa-imdb fa-fw",
  "fa-brands fa-hubspot fa-fw",
  "fa-brands fa-houzz fa-fw",
  "fa-brands fa-hotjar fa-fw",
  "fa-brands fa-hornbill fa-fw",
  "fa-brands fa-hooli fa-fw",
  "fa-brands fa-hive fa-fw",
  "fa-brands fa-hire-a-helper fa-fw",
  "fa-brands fa-hips fa-fw",
  "fa-brands fa-hashnode fa-fw",
  "fa-brands fa-hackerrank fa-fw",
  "fa-brands fa-hacker-news fa-fw",
  "fa-brands fa-gulp fa-fw",
  "fa-brands fa-guilded fa-fw",
  "fa-brands fa-grunt fa-fw",
  "fa-brands fa-gripfire fa-fw",
  "fa-brands fa-grav fa-fw",
  "fa-brands fa-gratipay fa-fw",
  "fa-brands fa-google-wallet fa-fw",
  "fa-brands fa-google-plus-g fa-fw",
  "fa-brands fa-google-plus fa-fw",
  "fa-brands fa-google-pay fa-fw",
  "fa-brands fa-google-drive fa-fw",
  "fa-brands fa-goodreads fa-fw",
  "fa-brands fa-golang fa-fw",
  "fa-brands fa-gofore fa-fw",
  "fa-brands fa-glide fa-fw",
  "fa-brands fa-gitter fa-fw",
  "fa-brands fa-gitkraken fa-fw",
  "fa-brands fa-github-alt fa-fw",
  "fa-brands fa-git-alt fa-fw",
  "fa-brands fa-git fa-fw",
  "fa-brands fa-gg-circle fa-fw",
  "fa-brands fa-gg fa-fw",
  "fa-brands fa-get-pocket fa-fw",
  "fa-brands fa-galactic-senate fa-fw",
  "fa-brands fa-galactic-republic fa-fw",
  "fa-brands fa-fulcrum fa-fw",
  "fa-brands fa-freebsd fa-fw",
  "fa-brands fa-foursquare fa-fw",
  "fa-brands fa-forumbee fa-fw",
  "fa-brands fa-fort-awesome-alt fa-fw",
  "fa-brands fa-fort-awesome fa-fw",
  "fa-brands fa-fonticons-fi fa-fw",
  "fa-brands fa-fonticons fa-fw",
  "fa-brands fa-font-awesome fa-fw",
  "fa-brands fa-flipboard fa-fw",
  "fa-brands fa-flickr fa-fw",
  "fa-brands fa-firstdraft fa-fw",
  "fa-brands fa-first-order-alt fa-fw",
  "fa-brands fa-first-order fa-fw",
  "fa-brands fa-firefox-browser fa-fw",
  "fa-brands fa-firefox fa-fw",
  "fa-brands fa-fedora fa-fw",
  "fa-brands fa-fedex fa-fw",
  "fa-brands fa-fantasy-flight-games fa-fw",
  "fa-brands fa-facebook-f fa-fw",
  "fa-brands fa-expeditedssl fa-fw",
  "fa-brands fa-evernote fa-fw",
  "fa-brands fa-ethereum fa-fw",
  "fa-brands fa-erlang fa-fw",
  "fa-brands fa-envira fa-fw",
  "fa-brands fa-ember fa-fw",
  "fa-brands fa-ello fa-fw",
  "fa-brands fa-edge-legacy fa-fw",
  "fa-brands fa-edge fa-fw",
  "fa-brands fa-ebay fa-fw",
  "fa-brands fa-earlybirds fa-fw",
  "fa-brands fa-dyalog fa-fw",
  "fa-brands fa-drupal fa-fw",
  "fa-brands fa-draft2digital fa-fw",
  "fa-brands fa-dochub fa-fw",
  "fa-brands fa-digital-ocean fa-fw",
  "fa-brands fa-digg fa-fw",
  "fa-brands fa-diaspora fa-fw",
  "fa-brands fa-dhl fa-fw",
  "fa-brands fa-deviantart fa-fw",
  "fa-brands fa-dev fa-fw",
  "fa-brands fa-deskpro fa-fw",
  "fa-brands fa-deploydog fa-fw",
  "fa-brands fa-delicious fa-fw",
  "fa-brands fa-deezer fa-fw",
  "fa-brands fa-dailymotion fa-fw",
  "fa-brands fa-d-and-d-beyond fa-fw",
  "fa-brands fa-d-and-d fa-fw",
  "fa-brands fa-cuttlefish fa-fw",
  "fa-brands fa-css3-alt fa-fw",
  "fa-brands fa-css3 fa-fw",
  "fa-brands fa-critical-role fa-fw",
  "fa-brands fa-creative-commons-zero fa-fw",
  "fa-brands fa-creative-commons-share fa-fw",
  "fa-brands fa-creative-commons-sampling-plus fa-fw",
  "fa-brands fa-creative-commons-sampling fa-fw",
  "fa-brands fa-creative-commons-sa fa-fw",
  "fa-brands fa-creative-commons-remix fa-fw",
  "fa-brands fa-creative-commons-pd-alt fa-fw",
  "fa-brands fa-creative-commons-pd fa-fw",
  "fa-brands fa-creative-commons-nd fa-fw",
  "fa-brands fa-creative-commons-nc-jp fa-fw",
  "fa-brands fa-creative-commons-nc-eu fa-fw",
  "fa-brands fa-creative-commons-nc fa-fw",
  "fa-brands fa-creative-commons-by fa-fw",
  "fa-brands fa-creative-commons fa-fw",
  "fa-brands fa-cpanel fa-fw",
  "fa-brands fa-cotton-bureau fa-fw",
  "fa-brands fa-contao fa-fw",
  "fa-brands fa-connectdevelop fa-fw",
  "fa-brands fa-confluence fa-fw",
  "fa-brands fa-codiepie fa-fw",
  "fa-brands fa-cmplid fa-fw",
  "fa-brands fa-cloudversify fa-fw",
  "fa-brands fa-cloudsmith fa-fw",
  "fa-brands fa-cloudscale fa-fw",
  "fa-brands fa-chromecast fa-fw",
  "fa-brands fa-chrome fa-fw",
  "fa-brands fa-centos fa-fw",
  "fa-brands fa-centercode fa-fw",
  "fa-brands fa-cc-stripe fa-fw",
  "fa-brands fa-cc-paypal fa-fw",
  "fa-brands fa-cc-jcb fa-fw",
  "fa-brands fa-cc-discover fa-fw",
  "fa-brands fa-cc-diners-club fa-fw",
  "fa-brands fa-cc-apple-pay fa-fw",
  "fa-brands fa-cc-amex fa-fw",
  "fa-brands fa-cc-amazon-pay fa-fw",
  "fa-brands fa-canadian-maple-leaf fa-fw",
  "fa-brands fa-buysellads fa-fw",
  "fa-brands fa-buy-n-large fa-fw",
  "fa-brands fa-buromobelexperte fa-fw",
  "fa-brands fa-buffer fa-fw",
  "fa-brands fa-btc fa-fw",
  "fa-brands fa-bots fa-fw",
  "fa-brands fa-bootstrap fa-fw",
  "fa-brands fa-bluetooth-b fa-fw",
  "fa-brands fa-bluetooth fa-fw",
  "fa-brands fa-blogger-b fa-fw",
  "fa-brands fa-blogger fa-fw",
  "fa-brands fa-blackberry fa-fw",
  "fa-brands fa-black-tie fa-fw",
  "fa-brands fa-bity fa-fw",
  "fa-brands fa-bitcoin fa-fw",
  "fa-brands fa-bitbucket fa-fw",
  "fa-brands fa-bimobject fa-fw",
  "fa-brands fa-bilibili fa-fw",
  "fa-brands fa-battle-net fa-fw",
  "fa-brands fa-bandcamp fa-fw",
  "fa-brands fa-aws fa-fw",
  "fa-brands fa-aviato fa-fw",
  "fa-brands fa-avianex fa-fw",
  "fa-brands fa-autoprefixer fa-fw",
  "fa-brands fa-audible fa-fw",
  "fa-brands fa-asymmetrik fa-fw",
  "fa-brands fa-artstation fa-fw",
  "fa-brands fa-apple-pay fa-fw",
  "fa-brands fa-apper fa-fw",
  "fa-brands fa-app-store-ios fa-fw",
  "fa-brands fa-app-store fa-fw",
  "fa-brands fa-angular fa-fw",
  "fa-brands fa-angrycreative fa-fw",
  "fa-brands fa-angellist fa-fw",
  "fa-brands fa-amilia fa-fw",
  "fa-brands fa-amazon-pay fa-fw",
  "fa-brands fa-alipay fa-fw",
  "fa-brands fa-affiliatetheme fa-fw",
  "fa-brands fa-adversal fa-fw",
  "fa-brands fa-adn fa-fw",
  "fa-brands fa-accusoft fa-fw",
  "fa-brands fa-500px fa-fw",
  "fa-brands fa-42-group fa-fw",
  "fa-brands fa-empire fa-fw",
];
export const guideType = [];
